### ISSUE TITLE
[FR] M$ Exchange / ActiveSync support

### ISSUE THREAD

**Issue by ildar** [M66B/open-source-email#69] opened 2018-08-30 20:39 UTC
I see FAQ says it's not yet supported.
So created this FR to track this feature.
Have any ideas on it?

**Comment by M66B** [comment] 2018-09-08 12:09
The problem with this is that there are hardly any decent Java libraries for this.

There is a very old Google implementation here:
https://android.googlesource.com/platform/packages/apps/Email/+/froyo/src/com/android/exchange/

If you can find a recent and maintained Java library please let me know.

Exchange supports IMAP too, if the administrator enabled it, so this is not a big issue.

**Comment by M66B** [comment] 2018-09-08 13:33
DavMail is more a gateway that a client, so this is not usable.

See above for a link to the very old Google code, which is the implementation of the Exchange account. The problem is that nobody maintains it.

**Comment by ildar** [comment] 2018-09-08 13:48
But I still see it in Android at least version 7. You sure it's abandoned?

**Comment by M66B** [comment] 2018-09-08 13:53
I am sure because there was nothing interesting committed in years, check here:
https://android.googlesource.com/platform/packages/apps/Email/+log/master

**Comment by M66B** [comment] 2018-09-13 08:15
For now there is not enough support for this project to justify putting effort into this.

**Closed by M66B** 2018-09-13 08:15 UTC
