### ISSUE TITLE
Forward, Reply, Reply All, New Mail - trash icon can't be pressed

### ISSUE THREAD

**Issue by licaon-kter** [M66B/open-source-email#7] opened 2018-08-02 22:59 UTC

**Comment by M66B** [comment] 2018-08-03 06:26
Works for me. Please provide more details.

**Comment by licaon-kter** [comment] 2018-08-03 07:25
Albeit it works if I open a draft from the Drafts folder.

**Comment by M66B** [comment] 2018-08-03 07:27
So, when doesn't it work?

**Comment by licaon-kter** [comment] 2018-08-03 07:31
New mail via orange icon - not
See an email - press forward/reply/replyall - not

**Comment by M66B** [comment] 2018-08-03 08:05
By email with video:
> (for some reason my ROM refuses to "show touches"
> 
> Steps:
> I write the texts
> Long press send (but me away so it does not trigger)
> Long press save as draft
> Long press trash (no animation nor action on touch)

Can you please reproduce the problem and send me the debug information?

**Comment by M66B** [comment] 2018-08-04 16:43
Should be fixed.

**Closed by M66B** 2018-08-04 16:43 UTC

**Comment by licaon-kter** [comment] 2018-08-05 19:57
Fixed, thanks
