### ISSUE TITLE
UNIQUE constraint failed: message.msgid, message.folder

### ISSUE THREAD

**Issue by licaon-kter** [M66B/open-source-email#41] opened 2018-08-16 15:58 UTC
0.14

```
V fairemail: INBOX end sync
E fairemail: TEST android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: message.msgid, message.folder (Sqlite code 2067), (OS error - 0:Success)
E fairemail: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: message.msgid, message.folder (Sqlite code 2067), (OS error - 0:Success)
E fairemail: 	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
E fairemail: 	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:818)
E fairemail: 	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:803)
E fairemail: 	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
E fairemail: 	at androidx.q.a.a.e.c(SourceFile:51)
E fairemail: 	at androidx.o.i.insertAndReturnId(SourceFile:114)
E fairemail: 	at eu.faircode.email.DaoMessage_Impl.insertMessage(SourceFile:420)
E fairemail: 	at eu.faircode.email.ServiceSynchronize.synchronizeMessage(SourceFile:1297)
E fairemail: 	at eu.faircode.email.ServiceSynchronize.synchronizeMessages(SourceFile:1172)
E fairemail: 	at eu.faircode.email.ServiceSynchronize.monitorAccount(SourceFile:505)
E fairemail: 	at eu.faircode.email.ServiceSynchronize.access$1300(SourceFile:111)
E fairemail: 	at eu.faircode.email.ServiceSynchronize$ServiceManager$3$1.run(SourceFile:1414)
E fairemail: 	at java.lang.Thread.run(Thread.java:784)
```

**Comment by M66B** [comment] 2018-08-16 16:13
Was this after sending a message?

**Comment by licaon-kter** [comment] 2018-08-16 16:34
No, updated, open... got 4 emails...
Emails were not marked as read if opened

I FC and clean cache, reopen, read the emails, sent one...then notification hell started again..had to FC

**Comment by M66B** [comment] 2018-08-16 16:36
Can you please provide a log file?

The problem is that there is a message ID duplicate. It is easy to "fix" by replacing the previously stored message, but this shouldn't happen in the first place. So, I like to know what is going on instead of using an easy fix only to discover later it caused more problems that it solved.

**Comment by licaon-kter** [comment] 2018-08-16 16:51
I can't ATM

The log has days of info that I can't edit now.

Also, opening about-debug, switch here, switch back yielded another crash email to be sent about `small parcel` and now opening the debug screen opens an empty view and the toast says `Couln't read row 0, col 6 from CursorWindow. Make sure the Cursor is initialized correctly before accesing data from it.`

**Comment by M66B** [comment] 2018-08-16 16:54
The small parcel problem, same as in NetGuard, cannot be fixed. The cursor problem is related. It just means that a certain memory type has been exhausted. You should consider it a bug in your Android version.

Can you please describe in details what you did, like upgrade, do this, do that, etc?

**Comment by licaon-kter** [comment] 2018-08-16 16:58
I already did see above, there's nothing to add.

Again, after I enabled debug in Settings and about-debug yielded that big email with the log, then this error happened.

**Comment by licaon-kter** [comment] 2018-08-16 16:58
I'll do a cleanup and resetup 🙄

**Comment by M66B** [comment] 2018-08-16 17:41
I am able to reproduce this problem and working on a solution.

**Comment by M66B** [comment] 2018-08-16 18:29
Fixed in 0.15

https://github.com/M66B/open-source-email/releases/tag/0.15

**Comment by licaon-kter** [comment] 2018-08-16 19:34
Please reopen, 0.15 still has this

```
V fairemail: INBOX end sync
E fairemail: AE android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: message.msgid, message.folder (Sqlite code 2067), (OS error - 0:Success)
E fairemail: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: message.msgid, message.folder (Sqlite code 2067), (OS error - 0:Success)
E fairemail: 	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
E fairemail: 	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:818)
E fairemail: 	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:803)
E fairemail: 	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
E fairemail: 	at androidx.q.a.a.e.c(SourceFile:51)
E fairemail: 	at androidx.o.i.insertAndReturnId(SourceFile:114)
E fairemail: 	at eu.faircode.email.DaoMessage_Impl.insertMessage(SourceFile:420)
E fairemail: 	at eu.faircode.email.ServiceSynchronize.synchronizeMessage(SourceFile:1297)
E fairemail: 	at eu.faircode.email.ServiceSynchronize.synchronizeMessages(SourceFile:1173)
E fairemail: 	at eu.faircode.email.ServiceSynchronize.monitorAccount(SourceFile:506)
E fairemail: 	at eu.faircode.email.ServiceSynchronize.access$1300(SourceFile:112)
E fairemail: 	at eu.faircode.email.ServiceSynchronize$ServiceManager$3$1.run(SourceFile:1414)
E fairemail: 	at java.lang.Thread.run(Thread.java:784)
```

**Comment by M66B** [comment] 2018-08-16 19:46
I think it is unlikely that 0.15 still has this problem, but you'll never know. Please provide a log file.

**Comment by M66B** [comment] 2018-08-16 19:50
It could be caused by database corruption from a previous version, so maybe clear data and start over again.

**Comment by licaon-kter** [comment] 2018-08-16 20:02
I did clear...

It will take some time until I can get a log though.

**Comment by M66B** [comment] 2018-08-17 04:53
Did you configure multiple accounts having the same message multiple times?

**Comment by licaon-kter** [comment] 2018-08-17 05:02
Nope, just 1 account

**Comment by M66B** [comment] 2018-08-20 08:46
I haven't been able to reproduce this problem and nobody else reported this problem. So, are you sure you are using the latest version and that you did clear data?

**Comment by licaon-kter** [comment] 2018-08-20 08:50
Unfortunately yes, I'll see about that log.

**Comment by M66B** [comment] 2018-08-20 09:50
I did some changes, so hopefully the next release will fix the problem, else I will need to see a logcat.

**Comment by licaon-kter** [comment] 2018-08-21 14:41
Sending that email to Trash allowed FairMail to sync them rest of the inbox.

**Comment by M66B** [comment] 2018-08-22 07:00
Can you please try if version 0.16 fixed the problem?

https://github.com/M66B/open-source-email/releases

**Closed** 2018-08-23 13:49 UTC

**Comment by licaon-kter** [comment] 2018-08-23 14:57
Brought the e-mail back with K-9 and FairMail doesn't show it.

**Comment by M66B** [comment] 2018-08-23 14:58
So, the problem is solved?

**Comment by licaon-kter** [comment] 2018-08-23 15:18
:))

How would I know?

**Comment by M66B** [comment] 2018-08-23 15:19
I guess this is related to #37
