### ISSUE TITLE
Reply-to field in Compose message

### ISSUE THREAD

**Issue by heinhuiz** [M66B/open-source-email#140] opened 2018-09-22 18:27 UTC
Ref. title.
Preferably located below the CC: and BCC: fields.

**Comment by CircleCode** [comment] 2018-09-24 10:57
as described in #143: if you fix this issue, please do not restrict it to the REPLY-TO field and also include at least FROM

**Comment by M66B** [comment] 2018-09-24 11:27
I am considering this as a duplicate of #143
The use case is to use a different from field for different destinations.

**Closed by M66B** 2018-09-24 11:27 UTC
Labels: TBD
