### ISSUE TITLE
Logo Design: Open Source Email

### ISSUE THREAD

**Issue by baranpirincal** [M66B/open-source-email#98] opened 2018-09-08 09:59 UTC
Hey!

I am graphic designer and I want to improve quality of my portfolio with supporting open-source projects. I can design a new logo for Open Source Email. What do you think about it? I am waiting your comments!

Best Regards
Baran

**Comment by M66B** [comment] 2018-09-08 10:02
Duplicate of #25

**Closed by M66B** 2018-09-08 10:02 UTC
