### ISSUE TITLE
[FR] Exclude an account from the Unified inbox

### ISSUE THREAD

**Issue by Primokorn** [M66B/open-source-email#60] opened 2018-08-28 14:33 UTC
One of my accounts receive many emails and I'd like to exclude it from the Unified inbox to keep it clean.
I would just have to open the drawer to go into its inbox and other folders.

Thanks.

**Comment by licaon-kter** [comment] 2018-08-28 14:39
https://github.com/M66B/open-source-email/issues/47 ?

**Comment by Primokorn** [comment] 2018-08-28 14:41
@licaon-kter No. I want to keep the Unified Inbox but only with 7 of my 8 accounts.

**Comment by M66B** [comment] 2018-09-04 13:51
This is a duplicate of #47 because by selecting which inboxes to show you can select 7 of your 8 accounts.

**Closed by M66B** 2018-09-04 13:51 UTC

**Comment by Primokorn** [comment] 2018-09-05 07:30
@M66B Notifications for the excluded account could also be disabled?

**Comment by M66B** [comment] 2018-09-05 07:33
@Primokorn please add this request to #47
