### ISSUE TITLE
Add icons or text for swipe actions on mails for better UX

### ISSUE THREAD

**Issue by ouzowtf** [M66B/open-source-email#84] opened 2018-09-04 12:38 UTC
It was mentioned in the XDA thread already, but I did not find a GitHub issue for it.

For better UX it would be nice if the swipe actions could show a visual hint in the free space like an icon or text to better teach the user which action he performs at the moment.
Personally I can't remember if trash or archive is left or right swipe, even if you told me just one minute ago :sweat_smile:

**Comment by M66B** [comment] 2018-09-04 12:39
Duplicate of #59

**Closed by M66B** 2018-09-04 12:39 UTC

**Comment by ouzowtf** [comment] 2018-09-04 12:44
OMG, I'm sorry.
I promise to search better the next time :disappointed:
