### ISSUE TITLE
[Pro features]  Preview sender/subject in new messages status bar notification

### ISSUE THREAD

**Issue by Glops94** [M66B/open-source-email#85] opened 2018-09-04 13:31 UTC
the ability to choose the number of lines to display for me a single line (the sender and the subject) is more than enough

**Comment by M66B** [comment] 2018-09-04 13:43
I am not sure what you mean. The status bar notification already shows the sender/subject/time, at least if you have the pro features.

**Comment by M66B** [comment] 2018-09-05 09:43
I guess this is a duplicate of #89

**Closed by M66B** 2018-09-05 09:43 UTC
